### Lookup Coordinates By Address
GET {{baseUrl}}/{{apiPrefix}}/geo/coordinates?address=동천역
Accept: application/json

###

### Transit Routes Search
POST {{baseUrl}}/{{apiPrefix}}/geo/transit/routes
Accept: application/json
Content-Type: application/json

{
  "startX": "127.101132",
  "startY": "37.516538",
  "endX": "127.098593",
  "endY": "37.346791",
  "count": 10,
  "lang": 0,
  "format": "json"
}
